databases:
  - name: job_portal_db
    databaseName: job_portal
    user: job_portal_user
    plan: free
    region: singapore

services:
  - type: web
    name: job-portal
    env: docker
    region: singapore
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: job_portal_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: '*'
